# TOML results file for parKVFinder software

title = "parKVFinder results file"

[FILES_PATH]
INPUT = "/home/jvsguerra/remote-repos/kvfinder-ws/client/1HVR.pdb"
OUTPUT = "/home/jvsguerra/remote-repos/kvfinder-ws/client/550353461108510246/output.KVFinder.output.pdb"

[PARAMETERS]
RESOLUTION = "Low"
STEP_SIZE = 0.6

[RESULTS.VOLUME]
KAA = 6.05
KAB = 650.16
KAC = 9.07

[RESULTS.AREA]
KAA = 4.15
KAB = 147.55
KAC = 5.47

[RESULTS.RESIDUES]
KAA = [ [ "65", "B", "E",], [ "14", "B", "K",], [ "15", "B", "I",], [ "16", "B", "G",], [ "63", "B", "L",], [ "64", "B", "I",],]
KAB = [ [ "84", "B", "I",], [ "8", "A", "R",], [ "23", "A", "L",], [ "25", "A", "D",], [ "27", "A", "G",], [ "28", "A", "A",], [ "29", "A", "D",], [ "30", "A", "D",], [ "32", "A", "V",], [ "47", "A", "I",], [ "48", "A", "G",], [ "49", "A", "G",], [ "50", "A", "I",], [ "76", "A", "L",], [ "80", "A", "T",], [ "81", "A", "P",], [ "82", "A", "V",], [ "84", "A", "I",], [ "8", "B", "R",], [ "23", "B", "L",], [ "25", "B", "D",], [ "27", "B", "G",], [ "28", "B", "A",], [ "29", "B", "D",], [ "30", "B", "D",], [ "32", "B", "V",], [ "47", "B", "I",], [ "48", "B", "G",], [ "49", "B", "G",], [ "50", "B", "I",], [ "76", "B", "L",], [ "80", "B", "T",], [ "81", "B", "P",], [ "82", "B", "V",],]
KAC = [ [ "65", "A", "E",], [ "14", "A", "K",], [ "15", "A", "I",], [ "16", "A", "G",], [ "63", "A", "L",], [ "64", "A", "I",],]
