[package]
name = "kv_web"
version = "0.1.0"
authors = ["jgcarvalho"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

